language: android
matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - mkdir ~/.m2
        - brew install danger/tap/danger-kotlin 
      script:
        - danger-kotlin ci
